package com.wynk.common;

import com.wynk.constants.JsonKeyNames;
import com.wynk.constants.MusicConstants;
import com.wynk.user.dto.UserActivityEvent;
import org.apache.commons.lang3.StringUtils;
import org.json.simple.JSONObject;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by bhuvangupta on 01/01/14.
 */
public enum UserEventType {

    ITEM_SEARCH("ITEM_SEARCH",0,null),
    APP_STARTED("APP_STARTED",0,null), APP_CLOSED("APP_CLOSED",0,null),APP_INSTALL("APP_INSTALL",17,null),
    SCREEN_OPENED("SCREEN_OPENED",0,null), SCREEN_CLOSED("SCREEN_CLOSED",0,null),
    CLICK("CLICK",1,null),
    SONG_PLAYED("SONG_PLAYED",2,"Listened to"), SONG_PAUSED("SONG_PAUSED",5,null),
    SONG_PLAYED_LONG("SONG_PLAYED_LONG",16,"Song played for N seconds"),
    SONG_COMPLETED("SONG_COMPLETED",6,"Listened to"),
    ITEM_QUEUED("ITEM_QUEUED",0,null), ITEM_DEQUEUED("ITEM_DEQUEUED",0,null),
    ITEM_ADDED_TO_PLAYLIST("SONG_ADDED_TO_PLAYLIST",0,null),
    ITEM_REMOVED_FROM_PLAYLIST("ITEM_REMOVED_FROM_PLAYLIST",0,null),
    ITEM_LIKED("ITEM_LIKED",7,"Likes"), ITEM_UNLIKED("ITEM_UNLIKED",0,null),
    //ITEM_FOLLOW("ITEM_FOLLOW",7,"Likes"), ITEM_UNFOLLOW("ITEM_UNFOLLOW",0,null),
    ITEM_SHARED("ITEM_SHARED",13,"Shared"),
    ITEM_RENTING_STARTED("ITEM_RENTING_STARTED",9,null),
    ITEM_RENTED("ITEM_RENTED",4,"Downloaded"),
    ITEM_REMOVED("ITEM_REMOVED",0,null),
    ITEM_DOWNLOAD_STARTED("ITEM_DOWNLOAD_STARTED",9,null),
    ITEM_DOWNLOADED("ITEM_DOWNLOADED",10,"Purchased"),
    ITEM_DELETED("ITEM_DELETED",0,null),
    ITEM_RENTING_FAILED("ITEM_RENTING_FAILED",0,null),
    ITEM_DOWNLOADING_FAILED("ITEM_DOWNLOADING_FAILED",0,null),
    ITEM_RADIO_STARTED("ITEM_RADIO_STARTED",0,null), RADIO_STARTED("RADIO_STARTED",0,null), RADIO_STOPPED("RADIO_STOPPED",0,null),
    USER_PROFILE_CREATED("USER_PROFILE_CREATED",0,null), USER_PROFILE_EDITED("USER_PROFILE_EDITED",0,null),
    USER_PLAYLIST_CREATED("USER_PLAYLIST_CREATED",0,"Created playlist"), USER_PLAYLIST_UPDATED("USER_PLAYLIST_UPDATED",0,null),
    USER_PLAYLIST_ADD_SONGS("USER_PLAYLIST_ADD_SONGS",0,null),
    USER_PLAYLIST_REMOVE_SONGS("USER_PLAYLIST_REMOVE_SONGS",0,null),
    USER_PLAYLIST_DELETED("USER_PLAYLIST_DELETED",0,null),
    PAGE_LOADED("PAGE_LOADED",0,null), PAGE_FAILED("PAGE_FAILED",0,null),
    NOTIFICATION_READ("NOTIFICATION_READ",15,"Notification Ready by User"),
    NOTIFICATION_RECEIVED("NOTIFICATION_RECEIVED",18,"Notification Received by User"),
    NOTIFICATION_SHOWN("NOTIFICATION_SHOWN",19,"Notification seen by user"),
    SOS("SOS",20,"SOS"),
    APP_INSTALL_APPS_FLYER("APP_INSTALL_APPS_FLYER", 98, "AppsFlyer install events"),
    APP_INSTALL_BE("APP_INSTALL_BE",21,"APP_INSTALL_BE"),
    MODULE_SHOWN("MODULE_SHOWN",22,"MODULE_SHOWN"),
    SONG_ENDED("SONG_ENDED",24,null),
    LANG_CHANGED("LANG_CHANGED", 23, "LANG_CHANGED"),
    FILE_DELETED("FILE_DELETED", 25, "FILE_DELETED"),
    REGISTRATION_ABANDONED("REGISTRATION_ABANDONED", 26, "REGISTRATION_ABANDONED"),
    REGISTRATION_FAILED("REGISTRATION_FAILED", 27, "REGISTRATION_FAILED"),
    APP_EXT_INSTALL("APP_EXT_INSTALL", 28, "APP_EXT_INSTALL"),
    GCM_REGISTRATION_FAILED("GCM_REGISTRATION_FAILED", 29, "GCM_REGISTRATION_FAILED"),
    GCM_EXPIRED("GCM_EXPIRED", 30, "GCM_EXPIRED"),
    GCM_REGISTRATION_SUCCESSFUL("GCM_REGISTRATION_SUCCESSFUL", 31, "GCM_REGISTRATION_SUCCESSFUL"),
    URBAN_AIRSHIP_CHANNEL_UPDATED("URBAN_AIRSHIP_CHANNEL_UPDATED", 32, "URBAN_AIRSHIP_CHANNEL_UPDATED"),
    AUTO_PLAY_BANNER_HIDDEN("AUTO_PLAY_BANNER_HIDDEN", 33, "AUTO_PLAY_BANNER_HIDDEN"),
    APP_BACKGROUND("APP_BACKGROUND", 34, "APP_BACKGROUND"),
    APP_FOREGROUND("APP_FOREGROUND", 35, "APP_FOREGROUND"),
    APP_UNINSTALL_BE("APP_UNINSTALL_BE",36,"APP_UNINSTALL_BE"),
    NOT_CONSUMED("NOT_CONSUMED", 37, "NOT_CONSUMED"),
    EMPTY_SESSION("EMPTY_SESSION", 38, "EMPTY_SESSION"),
    RESET("RESET", 39, "RESET"),
    EXTERNAL_ID("EXTERNAL_ID", 40, "EXTERNAL_ID"),
    APP_INFO("APP_INFO", 41, "APP_INFO"),
    REQUEST_TIME("REQUEST_TIME", 42, "REQUEST_TIME"),
    UNSUBSCRIBED("UNSUBSCRIBED", 43, "UNSUBSCRIBED"),
    REGISTERED("REGISTERED", 44, "REGISTERED"),
    DATA_SAVE_TOGGLE("DATA_SAVE_TOGGLE",45,"DATA_SAVE_TOGGLE"),    
    IMEI_NUMBER("IMEI_NUMBER",46,"IMEI_NUMBER"),
    SPOTLIGHT_INDEXING_FAILED("SPOTLIGHT_INDEXING_FAILED",47,"SPOTLIGHT_INDEXING_FAILED"),
    ADHM_PLAYLIST_CREATED("ADHM_PLAYLIST_CREATED",48,"ADHM_PLAYLIST_CREATED"),
    MUSIC_PREFERENCE_CHANGED("MUSIC_PREFERENCE_CHANGED",49,"MUSIC_PREFERENCE_CHANGED"),
    ONDEVICE_SONG_MATCHED("ONDEVICE_SONG_MATCHED",52,"ONDEVICE_SONG_MATCHED"),
    ONDEVICE_SONG_NOT_MATCHED("ONDEVICE_SONG_NOT_MATCHED",53,"ONDEVICE_SONG_NOT_MATCHED"),
    ONDEVICE_SONG_WRONGLY_MATCHED("ONDEVICE_SONG_WRONGLY_MATCHED",54,"ONDEVICE_SONG_WRONGLY_MATCHED"),
    SONGS_MAPPING("SONGS_MAPPING",55,"SONGS_MAPPING"),
    FILE_EXP_PLAYBACK_FAILED("FILE_EXP_PLAYBACK_FAILED",56,"FILE_EXP_PLAYBACK_FAILED"),
    FOLDER_PLAYLIST_CREATED("FOLDER_PLAYLIST_CREATED",57,"FOLDER_PLAYLIST_CREATED"),
    ON_DEVICE_SONG_SCAN("ON_DEVICE_SONG_SCAN",58,"ON_DEVICE_SONG_SCAN"),
    METADATA_MATCH("METADATA_MATCH",59,"METADATA_MATCH"),
    FINGERPRINT_MATCH("FINGERPRINT_MATCH",60,"FINGERPRINT_MATCH"),
    FINGERPRINT_COMPLETED("FINGERPRINT_COMPLETED",61,"FINGERPRINT_COMPLETED"),
    FFMPEG_DOWNLOADED("FFMPEG_DOWNLOADED",62,"FFMPEG_DOWNLOADED"),
    META_BATCH_PROCESSING("META_BATCH_PROCESSING",63,"META_BATCH_PROCESSING"),
    FINGERPRINT_BATCH_PROCESSING("FINGERPRINT_BATCH_PROCESSING",64,"FINGERPRINT_BATCH_PROCESSING"),
    OTHER_INSTALLED_APPS("OTHER_INSTALLED_APPS",64,"OTHER_INSTALLED_APPS"),
    DEV_STATS("DEV_STATS",66,"DEV_STATS"),
    AB_TESTING("AB_Testing",67,"AB_Testing"),
    AUTO_REGISTRATION("AUTO_REGISTRATION", 68, "AUTO_REGISTRATION"),
    USER_INFO_CHANGED("USER_INFO_CHANGED", 69, "USER_INFO_CHANGED"),
    RENTED_DISK_SPACE("RENTED_DISK_SPACE", 70, "RENTED_DISK_SPACE"),
    OTHER_INSTALLED_APPS_DATA("OTHER_INSTALLED_APPS_DATA",71,"OTHER_INSTALLED_APPS_DATA"),
    ITEM_PROACTIVE_CACHED("ITEM_PROACTIVE_CACHED",72,"ITEM_PROACTIVE_CACHED"),
    PLAYBACK_STARTED_FROM_CACHE("PLAYBACK_STARTED_FROM_CACHE",73,"PLAYBACK_STARTED_FROM_CACHE"),
    FLAKY_NETWORK_MODE("FLAKY_NETWORK_MODE",74,"FLAKY_NETWORK_MODE"),
    QUEUE_SIZE("QUEUE_SIZE",75,"QUEUE_SIZE"),
    NEW_USER_NOT_REGISTERED("NEW_USER_NOT_REGISTERED",76,"NEW_USER_NOT_REGISTERED"),
    USER_PROFILE_UPDATE("USER_PROFILE_UPDATE",77,"USER_PROFILE_UPDATE"),
    USER_DEVICE_ADD("USER_DEVICE_ADD",78,"USER_DEVICE_ADD"),
    USER_DEVICE_REMOVED("USER_DEVICE_REMOVED",79,"USER_DEVICE_REMOVED"),
    USER_DEVICE_UPDATE("USER_DEVICE_UPDATE",80,"USER_DEVICE_UPDATE"),
    USER_SUBSCRIPTION_TYPE("USER_SUBSCRIPTION_TYPE",81,"USER_SUBSCRIPTION_TYPE"),
    DFP_REQUEST_SEND("DFP_REQUEST_SEND", 90, "DFP_REQUEST_SEND"),
    DFP_RESPONSE_RECEIVED("DFP_RESPONSE_RECEIVED", 91, "DFP_RESPONSE_RECEIVED"),
    AD_MEDIA_DOWNLOAD("AD_MEDIA_DOWNLOAD", 92, "AD_MEDIA_DOWNLOAD"),
    PREROLL_PLAY_STARTED("PREROLL_PLAY_STARTED", 93, "PREROLL_PLAY_STARTED"),
    PREROLL_PLAYED_LONG("PREROLL_PLAYED_LONG", 94, "PREROLL_PLAYED_LONG"),
    PREROLL_COMPLETED("PREROLL_COMPLETED", 95, "PREROLL_COMPLETED"),
    PREROLL_VIEW_DISPLAYED("PREROLL_VIEW_DISPLAYED", 96, "PREROLL_VIEW_DISPLAYED"),
    PREROLL_SKIPPED("PREROLL_SKIPPED", 97, "PREROLL_SKIPPED"),
    PREROLL_PAUSED("PREROLL_PAUSED", 98, "PREROLL_PAUSED"),
    PREROLL_CTA_CLICK("PREROLL_CTA_CLICK", 99, "PREROLL_CTA_CLICK"),
    PREROLL_PERSISTENCE_VIEW_DISPLAYED("PREROLL_PERSISTENCE_VIEW_DISPLAYED", 100, "PREROLL_PERSISTENCE_VIEW_DISPLAYED"),
    PREROLL_PERSISTENCE_CTA_CLICK("PREROLL_PERSISTENCE_CTA_CLICK", 101, "PREROLL_PERSISTENCE_CTA_CLICK"),
    PREROLL_KNOW_MORE_CLICK("PREROLL_KNOW_MORE_CLICK", 102, "PREROLL_KNOW_MORE_CLICK"),
    PREROLL_PERSISTENCE_CTA_CANCEL("PREROLL_PERSISTENCE_CTA_CANCEL", 103, "PREROLL_PERSISTENCE_CTA_CANCEL"),
    AD_ERROR("AD_ERROR", 104, "AD_ERROR"),
    PREROLL_SLOT_MISSED("PREROLL_SLOT_MISSED", 105, "PREROLL_SLOT_MISSED"),
    CACHE_ADDED("CACHE_ADDED", 106, "CACHE_ADDED"),
    CACHE_REMOVED("CACHE_REMOVED", 107, "CACHE_REMOVED"),
    DISPLAY("DISPLAY", 108, "DISPLAY"),
    PREROLL_ENDED("PREROLL_ENDED", 109, "PREROLL_ENDED"),
    ITEM_SEARCH_CONSUMED("ITEM_SEARCH_CONSUMED",110,"ITEM_SEARCH_CONSUMED"),
    ONBOARDING("ONBOARDING",111,"ONBOARDING"),
    PLAYBACK_BEHAVIOUR_CHANGED("PLAYBACK_BEHAVIOUR_CHANGED",112,"PLAYBACK_BEHAVIOUR_CHANGED"),
    PS_CONTINUE("PS_CONTINUE",113,"PS_CONTINUE"),
    PS_OPEN("PS_OPEN",114,"PS_OPEN"),
    PS_TOS_CLICK("PS_TOS_CLICK",115,"PS_TOS_CLICK"),
    PS_PRIVACY_CLICK("PS_PRIVACY_CLICK",116,"PS_PRIVACY_CLICK"),
    ON_DEVICE_SONG_INFO("ON_DEVICE_SONG_INFO",117,"ON_DEVICE_SONG_INFO"),
    BATCH_SELECT_MODE("BATCH_SELECT_MODE",118,"BATCH_SELECT_MODE"),
    NETWORK_STATUS("NETWORK_STATUS",119,"NETWORK_STATUS"),
    ITEM_ADDED("ITEM_ADDED",120,"ITEM_ADDED"),
    IMPRESSION_RECORDED("IMPRESSION_RECORDED",121,"IMPRESSION_RECORDED"),
    CACHE_PURGED("CACHE_PURGED",122,"CACHE_PURGED"),
    HOOK_RESOURCE_DOWNLOADED("HOOK_RESOURCE_DOWNLOADED",123,"HOOK_RESOURCE_DOWNLOADED"),
    TRITON_RESPONSE_RECEIVED ("TRITON_RESPONSE_RECEIVED",124,"TRITON_RESPONSE_RECEIVED"),
    APP_UPDATED("APP_UPDATED",125,"APP_UPDATED"),
    SELECTED_LANGUAGE("SELECTED_LANGUAGE",126,"SELECTED_LANGUAGE"),
    THIRD_PARTY_NOTIFY_CALL("THIRD_PARTY_NOTIFY_CALL",128,"THIRD_PARTY_NOTIFY_CALL"),
    INTL_ROAMING("INTL_ROAMING",129,"INTL_ROAMING"),
    STREAM_BLOCKED("STREAM_BLOCKED",130,"STREAM_BLOCKED"),
    CHANGE_NUMBER("CHANGE_NUMBER",132,"CHANGE_NUMBER"),
    CODEGEN("CODEGEN",133,"CODEGEN"),
    GOOGLE_SUBSCRIPTION_SUCCESS("GOOGLE_SUBSCRIPTION_SUCCESS",134,"GOOGLE_SUBSCRIPTION_SUCCESS"),
    GOOGLE_SUBSCRIPTION_FAILED("GOOGLE_SUBSCRIPTION_FAILED",135,"GOOGLE_SUBSCRIPTION_FAILED"),
    HAPPY_HOUR("HAPPY_HOUR",136,"HAPPY_HOUR"),
    SIGNIN_ABANDONED("SIGNIN_ABANDONED",137,"SIGNIN_ABANDONED"),
    SIGNIN_FAILED("SIGNIN_FAILED",138,"SIGNIN_FAILED"),
    SIGNIN("SIGNIN",139,"SIGNIN"),
    IS_TARGETUSER("IS_TARGETUSER",140,"IS_TARGETUSER"),
    IS_USER("IS_USER",141,"IS_USER"),
    PERMISSION_DENIED("PERMISSION_DENIED",142,"PERMISSION_DENIED"),
    PS_CLICK_CONTINUE("PS_CLICK_CONTINUE",143,"PS_CLICK_CONTINUE"),
    RENT_DEV_STATS("RENT_DEV_STATS",144,"RENT_DEV_STATS"),
    AUTO_SUGGEST_CLICK("AUTO_SUGGEST_CLICK",145,"AUTO_SUGGEST_CLICK"),
    AUTO_SUGGEST_NOT_CLICK("AUTO_SUGGEST_NOT_CLICK",146,"AUTO_SUGGEST_NOT_CLICK"),
    AUTO_SUGGEST("AUTO_SUGGEST",147,"AUTO_SUGGEST"),
    REMOVE_ADS_FLOW("REMOVE_ADS_FLOW",148,"REMOVE_ADS_FLOW"),
    USER_PLAYLIST_RENAMED("USER_PLAYLIST_RENAMED",149,"USER_PLAYLIST_RENAMED"),
    ALLOWED_MCC_STREAM("ALLOWED_MCC_STREAM",150,"ALLOWED_MCC_STREAM"),
    AUTOREGISTER("AUTOREGISTER",151,"AUTOREGISTER"),
    WYNK_DIRECT("WYNK_DIRECT",152,"WYNK_DIRECT"),
    PERMISSION_POPUP_ACTION("PERMISSION_POPUP_ACTION",153,"PERMISSION_POPUP_ACTION"),
    AD_LEAD_CAPTURE("AD_LEAD_CAPTURE",152,"AD_LEAD_CAPTURE"),
    TRANSACTION("TRANSACTION",155,"TRANSACTION"),
    FCM_REGISTRATION_SUCCESSFUL("FCM_REGISTRATION_SUCCESSFUL",156,"FCM_REGISTRATION_SUCCESSFUL"),
    FCM_REGISTRATION_FAILED("FCM_REGISTRATION_FAILED",157,"FCM_REGISTRATION_FAILED"),
    AUTO_CHANGE("AUTO_CHANGE",158,"AUTO_CHANGE"),
    FOLLOW("FOLLOW",159,"FOLLOW"),
    QUEUE_HEADER_DOCKED("QUEUE_HEADER_DOCKED",160,"QUEUE_HEADER_DOCKED"),
    QUEUE_VIEWED("QUEUE_VIEWED",161,"QUEUE_VIEWED"),
    RAIL_CLICKED("RAIL_CLICKED",162,"RAIL_CLICKED"),
    RAIL_RECEIVED("RAIL_RECEIVED",163,"RAIL_RECEIVED"),
    RAIL_RENDERED("RAIL_RENDERED",164,"RAIL_RENDERED"),
    RAIL_VIEWED("RAIL_VIEWED",165,"RAIL_VIEWED"),
    RAIL_SCROLL("RAIL_SCROLL",166,"RAIL_SCROLL"),
    UNFOLLOW("UNFOLLOW",167,"UNFOLLOW"),
    SELECTED_QUALITY("SELECTED_QUALITY",168,"SELECTED_QUALITY"),
    WAP_SUBSCRIPTION("WAP_SUBSCRIPTION",158,"WAP_SUBSCRIPTION"),
    QUEUE_LAST_SONG("QUEUE_LAST_SONG",159,"QUEUE_LAST_SONG"),
    SELECTED_TIME("SELECTED_TIME",169,"SELECTED_TIME"),
    SHARE("SHARE",170,"SHARE"),
    SONG_DELETED("SONG_DELETED",171,"SONG_DELETED"),
    SONG_SKIP("SONG_SKIP",172,"SONG_SKIP"),
    MOBILE_CONNECT("MOBILE_CONNECT",173,"MOBILE_CONNECT"),
    UNKNOWN("UNKNOWN",0,null);


    private static Map<String, UserEventType> sIdToTypeMapping = new HashMap<String, UserEventType>();

    static {
        for (UserEventType type : UserEventType.values()) {
            sIdToTypeMapping.put(type.getId().toLowerCase(), type);
        }
    }
    UserEventType(String id, int analyticsId, String journeyAlias) {
        this.id = id;
        this.analyticsId= analyticsId;
        this.journeyAlias = journeyAlias;
    }


    private String id;
    private String journeyAlias;
    private int analyticsId;

    public String getId() {
        return id;
    }

    public static UserEventType get(String id) {
//        System.out.println("id : "+id);
        return sIdToTypeMapping.get(id.toLowerCase());
    }

    public String getJourneyAlias() {
        return journeyAlias;
    }

    public static boolean isValidUserJourneyEvent(UserActivityEvent event)
    {
        UserEventType eventType = event.getType();
        
        if(eventType == SONG_PLAYED || eventType == ITEM_LIKED || eventType == ITEM_SHARED || eventType == USER_PLAYLIST_CREATED)
            return true;
        
        if(eventType == CLICK)
        {
            JSONObject meta = event.getMeta();
            String moduleId = "";
            Object object = meta.get(JsonKeyNames.MODULE_ID);
            
            if(object instanceof String)
                moduleId = (String) meta.get(JsonKeyNames.MODULE_ID);
            
            if(StringUtils.isBlank(moduleId))
                return false;
            
            // For ITEM_RENTED
            if(MusicConstants.MODULE_ID_DOWNLOAD.equalsIgnoreCase(moduleId))
                return true;
            
            // For ITEM_DOWNLOADED
            if(MusicConstants.MODULE_ID_PURCHASED.equalsIgnoreCase(moduleId))
                return true;
            
        }
        
        return false;
    }
}
