package com.wynk.music.constants;

public enum MusicNotificationType {
    FUP_99, FUP_UNSUBSCRIBED, FUP_UNSUBSCRIBED_TOTAL, FUP_UNSUBSCRIBED_REMAINING, 
    FUP_99_TOTAL, FUP_99_REMAINING, FUP_99_REMAINING_TOTAL, FUP_99_DATACHARGES, 
    FUP_UNSUBSCRIBED_PURCHASE, FUP_95, FUP_95_TITLE, IFB_TITLE, IFB_TITLE_MESSAGE, IFB_BENIFIT_TITLE, 
    DATA_CHARGES, NODATA_CHARGES, IFB_STARTED, IFB_80, IFB_LIMIT, FUP_UNLIMITED, VALID_TILL,STREAMING_BENEFIT,
    DATA_BENEFIT,ACTIVE,INACTIVE,WYNK_MUSIC,WYNK_PLUS,WYNK_FREEDOM, CRITICAL_UPDATE_MESSAGE, CRITICAL_UPDATE_TITLE, 
    UPDATE_AVAILABLE_MESSAGE, UPDATE_AVAILABLE_TITLE, OTP_INVALID_TITLE, OTP_INVALID_MESSAGE, OTP_EXPIRED_TITLE, 
    OTP_EXPIRED_MESSAGE, DOWNLOAD_BENEFIT, OFFER_PACK_80,OFFER_PACK_90,OFFER_PACK_80_TITLE,OFFER_PACK_90_TITLE,
    OFFER_PACK_COMPLETED,OFFER_PACK_COMPLETED_TITLE, OFFER_PACK, OFFER_PACK_DETAIL1, OFFER_PACK_DETAIL2,
    ACTIVATION_OFFER_PACK,SPECIAL_DAY_OFFER_PACK, SUBSCRIBE, INFO_ACTIVATION_OFFER_PACK1,INFO_ACTIVATION_OFFER_PACK2,
    INFO_SPECIAL_DAY_OFFER_PACK1,INFO_SPECIAL_DAY_OFFER_PACK2,
    UNSUBSCRIBE, CANCEL, CHANGE_PLAN, UNSUBSCRIBE_ACTIVE_LINE1, UNSUBSCRIBE_ACTIVE_LINE2, UNSUBSCRIBE_INACTIVE_LINE1, 
    UNSUBSCRIBE_INACTIVE_LINE2, UNSUBSCRIBE_PENDING_LINE1, UNSUBSCRIBE_PENDING_LINE2, CHANGE_PLAN_LINE1, CHANGE_PLAN_LINE2,
    UNSUBSCRIBE_FAILURE1,UNSUBSCRIBE_FAILURE2,UNSUBSCRIBE_SUCCESS1,UNSUBSCRIBE_SUCCESS2,UNSUBSCRIBE_INVALID_PRODUCT_ID1
    ,UNSUBSCRIBE_INVALID_PRODUCT_ID2,UNSUBSCRIBE_FAILURE_HEADER,UNSUBSCRIBE_SUCCESS_HEADER, WYNK_FREE_INFO1, WYNK_FREE_INFO2,
    WYNK_FREE_INFO_OFFER_AVAILED, WYNK_FREE_INFO_OFFER_NOT_AVAILED, WYNK_NEW_FREE_INFO_OFFER_NOT_AVAILED, INFO, BENEFIT, BENEFIT_1, BENEFIT_29_2, BENEFIT_7,
    BENEFIT_129_2,WYNK_FUP_SUBS_INFO1, WYNK_FUP_UNSUBS_INFO1, WYNK_FUP_UNSUBS_INFO2, WYNK_129_STATUS, STATUS, SUBS_VALID_TILL,
    INACTIVE_INFO_2, INACTIVE_INFO_3, INACTIVE_SUBSCRIBED_INFO, INACTIVE_UNSUBSCRIBED_INFO, CONTINUE,
    PROMO_CODE_INVALID, PROMO_CODE_USED, PROMO_CODE_EXPIRED, PROMO_CODE_NON_AIRTEL, PROMO_CODE_SUCCESS, PROMO_CODE_ICR_ERROR, WYNK_PLUS_4G,
    ITUNES_RENEW,WYNK_PLUS_FREE, WYNK_PLUS_FREE_NOBRACKETS, NOT_BEEN_CHARGED,RENEW,UPGRADE,DEACTIVATED,AUTORENEWAL,VALID_TILL_DATE,DEACTIVATE,PROMO_CODE_INVALID_COUPON,
    PROMO_CODE_INPROGRESS,PROMO_CODE_SERVER_ERROR,PROMO_CODE_REGISTRATION_REQUIRED,SEND_OTP, PURCHASE_AIRTEL_BILLING;
}
